name: RAILWAY TOKEN

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci # Use npm ci for consistent installs

      - name: Install development dependencies
        run: npm install mongodb-memory-server --save-dev

      - name: Run tests
        run: npm test
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          PORT: 5000 # 
          RATE_LIMIT_MAX: 100

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Deploy to Railway (only if tests pass)
        if: success()
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: railway up fintech-dashboard
